### ISSUE TITLE
Cannot read property ‘fd’ of null

### ISSUE THREAD

**Issue by honcheng** [noelportugal/google-home-notifier#16]
I’m not able to run the example.js. 
Getting this error. I made sure I have the latest version of nodejs. 

{ text: 'Hello Google Home' }
TypeError: Cannot read property 'fd' of null
    at Browser.start (/home/pi/google-home-notifier/node_modules/mdns/lib/mdns_service.js:32:35)
    at Object.notify (/home/pi/google-home-notifier/google-home-notifier.js:23:13)
    at /home/pi/google-home-notifier/example.js:20:16
    at Layer.handle [as handle_request] (/home/pi/google-home-notifier/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/pi/google-home-notifier/node_modules/express/lib/router/route.js:137:13)
    at /home/pi/google-home-notifier/node_modules/body-parser/lib/read.js:130:5
    at invokeCallback (/home/pi/google-home-notifier/node_modules/raw-body/index.js:262:16)
    at done (/home/pi/google-home-notifier/node_modules/raw-body/index.js:251:7)
    at IncomingMessage.onEnd (/home/pi/google-home-notifier/node_modules/raw-body/index.js:307:7)
    at emitNone (events.js:105:13)

**Comment by honcheng** [comment]
Problem goes away when reverting back to this commit ae2b118c8ebc89bd5b2484cb67ff9afc3ec24ac8

**Comment by tinoue** [comment]
The error occurs when google-home-notifier can't find Google Home by mDNS.
In my case my wifi access point disables all multicast transmission.

**Comment by kazhik** [comment]
If `service.name`('Google-Home-***') doesn't contain `device`(Google Home), browser is stopped.
Next call of browser.start() will throw `TypeError: Cannot read property 'fd' of null`.

```
  if (!deviceAddress){
     browser.start();
     browser.on('serviceUp', function(service) {
      console.log('Device "%s" at %s:%d', service.name, service.addresses[0], service.port);
      if (service.name.includes(device.replace(' ', '-'))){
        deviceAddress = service.addresses[0];
        getSpeechUrl(message, deviceAddress, function(res) {
          callback(res);
        });
      }
      browser.stop();

```

Fix: https://github.com/kazhik/google-home-notifier/commit/34e9f53a66d0923c392f604fb72d0f80285eac3c

**Comment by noelportugal** [comment]
Fixed in **v1.3.0** 🎉 — the native `mdns` dependency has been replaced with pure-JS [`bonjour-service`](https://www.npmjs.com/package/bonjour-service). No compilation, no avahi/Bonjour SDK, no patching `node_modules` — `npm install google-home-notifier` now works out of the box on macOS / Linux / Raspberry Pi / Windows. Please `npm i google-home-notifier@latest` and reopen if anything still bites.
