### ISSUE TITLE
No includes

### ISSUE THREAD

**Issue by edif30** [noelportugal/google-home-notifier#2]
@noelportugal 

Not sure why I am getting this.  I can run the example and it waits for commands.  Once I use curl, this is the output.  Another thing I noticed is it is only sometimes picking my ghome.  Other times it picks another cast device on my network.  Any ideas?

/tmp/google-home-notifier/google-home-notifier.js:17
      if (service.name.includes(device.replace(' ', '-'))){
                       ^
TypeError: Object Google-Home-5e7040daf543262437d19be8062f43d5 has no method 'includes'
    at Browser.<anonymous> (/tmp/google-home-notifier/google-home-notifier.js:17:24)
    at Browser.emit (events.js:98:17)
    at on_resolver_done (/tmp/google-home-notifier/node_modules/mdns/lib/browser.js:31:14)
    at next (/tmp/google-home-notifier/node_modules/mdns/lib/browser.js:104:7)
    at Array.makeAddressesUnique [as 2] (/tmp/google-home-notifier/node_modules/mdns/lib/resolver_sequence_tasks.js:177:5)
    at next (/tmp/google-home-notifier/node_modules/mdns/lib/browser.js:107:21)
    at /tmp/google-home-notifier/node_modules/mdns/lib/resolver_sequence_tasks.js:160:11
    at getaddrinfo_complete (/tmp/google-home-notifier/node_modules/mdns/lib/resolver_sequence_tasks.js:108:7)
    at Object.wrap.oncomplete (/tmp/google-home-notifier/node_modules/mdns/lib/resolver_sequence_tasks.js:130:7)

**Comment by noelportugal** [comment]
What OS are you using?

**Comment by edif30** [comment]
Fedora 23.  I think I am missing something because I am able to get it to work on my mac.

**Comment by noelportugal** [comment]
You might have to include these packages
libnss-mdns libavahi-compat-libdnssd-dev

**Comment by edif30** [comment]
I tried with dnf/yum but doesn't look like they are available.  Will have to do some digging.  Thanks!  BTW, got it working on the mac and it's pretty cool.  Gonna setup some rules and triggers with IFTTT.

**Comment by edif30** [comment]
I have both of them.  I gotta be missing something.

**Comment by lborensky** [comment]
I have a same problem on Raspberry Pi 3. After the 1st message sent (POST), the CPU remains at 100%. Does anyone have any idea of the problem?
