### ISSUE TITLE
Can't install from npm

### ISSUE THREAD

**Issue by kidapu** [noelportugal/google-home-notifier#43]
Can't install from `npm install` command. I can install other npm module. 
```
$ node --version                                     
v10.6.0
$ npm --version
2.15.1
$ npm install google-home-notifier
> mdns@2.4.0 install /Users/kidapu/00-DocRoot/02-projects/node_modules/google-home-notifier/node_modules/mdns
> node-gyp rebuild

gyp ERR! configure error
gyp ERR! stack Error: Python executable "/Users/kidapu/.pyenv/shims/python" is v3.4.3, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:406:14)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:395:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:282:7)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:380:11)
gyp ERR! stack     at Socket.emit (events.js:182:13)
gyp ERR! stack     at Pipe._handle.close (net.js:598:12)
gyp ERR! System Darwin 17.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/kidapu/00-DocRoot/02-projects/node_modules/google-home-notifier/node_modules/mdns
gyp ERR! node -v v10.6.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok

> ngrok@2.3.0 postinstall /Users/kidapu/00-DocRoot/02-projects/node_modules/google-home-notifier/node_modules/ngrok
> node ./postinstall.js

ngrok - unpacking binary
ngrok - binary unpacked to /Users/kidapu/00-DocRoot/02-projects/node_modules/google-home-notifier/node_modules/ngrok/bin/ngrok
npm ERR! Darwin 17.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "google-home-notifier"
npm ERR! node v10.6.0
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! mdns@2.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mdns@2.4.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the mdns package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mdns
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls mdns
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kidapu/00-DocRoot/02-projects/npm-debug.log
```

My OS is OSX 10.13.5.

**Comment by kokarn** [comment]
You've got an invalid python defined

gyp ERR! configure error
gyp ERR! stack Error: Python executable
"/Users/kidapu/.pyenv/shims/python" is v3.4.3, which is not supported
by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >=
v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion
(/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:406:14)
gyp ERR! stack     at
/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:395:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:282:7)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:380:11)
gyp ERR! stack     at Socket.emit (events.js:182:13)
gyp ERR! stack     at Pipe._handle.close (net.js:598:12)
gyp ERR! System Darwin 17.6.0
gyp ERR! command "/usr/local/bin/node"
"/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js"
"rebuild"
gyp ERR! cwd /Users/kidapu/00-DocRoot/02-projects/node_modules/google-home-notifier/node_modules/mdns
gyp ERR! node -v v10.6.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok

**Comment by kidapu** [comment]
@kokarn 

Thank you for your help!
I can install npm on python 2.7.15 

( And I can't install on python 2.5 )
