### ISSUE TITLE
Error: getaddrinfo -3008 with mdns

### ISSUE THREAD

**Issue by kasnyder98** [noelportugal/google-home-notifier#9]
I get the following when trying to run this:
============================
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo -3008
    at errnoException (/home/kelly/node_modules/mdns/lib/resolver_sequence_tasks.js:199:11)
    at getaddrinfo_complete (/home/kelly/node_modules/mdns/lib/resolver_sequence_tasks.js:112:10)
    at GetAddrInfoReqWrap.oncomplete (/home/kelly/node_modules/mdns/lib/resolver_sequence_tasks.js:120:9)
=========================

In researching this, I see lots of people having issues using mdns and end up using something else.

Anyone else get this?

**Comment by kasnyder98** [comment]
I got past this error for now by doing this:

https://stackoverflow.com/questions/29589543/raspberry-pi-mdns-getaddrinfo-3008-error

**Comment by kasnyder98** [comment]
I'm an idiot, this same resolution is already posted in the readme under "After "npm install""
